services:
  zybach.api:
    build:
      args:
        source: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Kestrel__Certificates__Default__Path=/https/host.docker.internal.pfx
      - Kestrel__Certificates__Default__Password=password#1
      - KEYSTONE_HOST=${KEYSTONE_HOST}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SITKA_EMAIL_REDIRECT=${SITKA_EMAIL_REDIRECT}
      - WEB_URL=${WEB_URL}
      - SECRET_PATH=${SECRET_PATH}
      - KEYSTONE_REDIRECT_URL=${KEYSTONE_REDIRECT_URL}
      - PlatformLongName=${PlatformLongName}
      - PlatformShortName=${PlatformShortName}
      - DoNotReplyEmail=${DoNotReplyEmail}
      - AppAlertsEmail=${AppAlertsEmail}
      - SupportEmail=${SupportEmail}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - GEOOPTIX_HOSTNAME=${GEOOPTIX_HOSTNAME}
      - AGHUB_API_BASE_URL=${AGHUB_API_BASE_URL}
      - AGHUB_API_BUCKET=${AGHUB_API_BUCKET}
      - GET_API_BASE_URL=${GET_API_BASE_URL}
      - GET_ROBUST_REVIEW_SCENARIO_RUN_CUSTOMER_ID=${GET_ROBUST_REVIEW_SCENARIO_RUN_CUSTOMER_ID}
      - GET_ROBUST_REVIEW_SCENARIO_RUN_USER_ID=${GET_ROBUST_REVIEW_SCENARIO_RUN_USER_ID}
      - GET_ROBUST_REVIEW_SCENARIO_RUN_MODEL_ID=${GET_ROBUST_REVIEW_SCENARIO_RUN_MODEL_ID}
      - GET_ROBUST_REVIEW_SCENARIO_RUN_SCENARIO_ID=${GET_ROBUST_REVIEW_SCENARIO_RUN_SCENARIO_ID}
      - VEGA_RENDER_URL=${VEGA_RENDER_URL}
      - OpenETAPIBaseUrl=${OpenETAPIBaseUrl}
      - OpenETRasterTimeSeriesMultipolygonRoute=${OpenETRasterTimeSeriesMultipolygonRoute}
      - OpenETRasterMetadataRoute=${OpenETRasterMetadataRoute}
      - OpenETAllFilesReadyForExportRoute=${OpenETAllFilesReadyForExportRoute}
      - OpenETGoogleBucketBaseURL=${OpenETGoogleBucketBaseURL}
      - OpenETRasterTimeseriesMultipolygonColumnToUseAsIdentifier=${OpenETRasterTimeseriesMultipolygonColumnToUseAsIdentifier}
    ports:
      - "8711:8080"
      - "8712:8081"
    volumes:
      - ~/.aspnet/https:/https:ro

  zybach.swagger:
    build:
      args:
        source: .
    ports:
      - "8715:8080"
      - "8716:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Kestrel__Certificates__Default__Path=/https/host.docker.internal.pfx
      - Kestrel__Certificates__Default__Password=password#1
      - SECRET_PATH=${SWAGGER_SECRET_PATH}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
    volumes:
      - ~/.aspnet/https:/https:ro

  geoserver:
    container_name: zybach_geoserver
    image: kartoza/geoserver:2.25.2
    environment:
      - ENABLE_JSONP=true
      - CATALINA_OPTS=-DALLOW_ENV_PARAMETRIZATION=true
      - ENV_PROPERTIES=/opt/geoserver/geoserver-environment.properties
      - STABLE_EXTENSIONS=sqlserver-plugin
      - TOMCAT_EXTRAS=false
      - ROOT_WEBAPP_REDIRECT=true
      - SAMPLE_DATA=false
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=${GeoserverAdminPassword}
    ports:
      - 127.0.0.1:8717:8080
    volumes:
      - c:/git/sitkatech/zybach/Zybach.GeoServer/data_dir:/opt/geoserver/data_dir
      - c:/sitka/zybach/GeoServer/geoserver-environment.properties:/opt/geoserver/geoserver-environment.properties

  vegarenderservice:
    container_name: zybach_vegarenderservice
    image: containersesaqa.azurecr.io/vegarenderservice:latest
    environment:
      - PORT=8090
    ports:
      - "8709:8080"
      - "8710:8081"