CREATE TABLE [dbo].[Well](
	[WellID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_Well_WellID] PRIMARY KEY,
	[WellRegistrationID] [varchar](100) NOT NULL CONSTRAINT [AK_Well_WellRegistrationID] UNIQUE,
	[WellGeometry] [geometry] NOT NULL,
	[StreamflowZoneID] [int] NULL CONSTRAINT [FK_Well_StreamFlowZone_StreamFlowZoneID] FOREIGN KEY REFERENCES [dbo].[StreamFlowZone] ([StreamFlowZoneID]),
	[CreateDate] [datetime] NOT NULL,
	[LastUpdateDate] [datetime] NULL,
	[WellNickname] [varchar](100) NULL,
	[TownshipRangeSection] [varchar](100) NULL,
	[CountyID] [int] NULL CONSTRAINT [FK_Well_County_CountyID] FOREIGN KEY REFERENCES [dbo].[County] ([CountyID]),
	[WellParticipationID] [int] NULL CONSTRAINT [FK_Well_WellParticipation_WellParticipationID] FOREIGN KEY REFERENCES [dbo].[WellParticipation] ([WellParticipationID]),
	[WellUseID] [int] NULL CONSTRAINT [FK_Well_WellUse_WellUseID] FOREIGN KEY REFERENCES [dbo].[WellUse] ([WellUseID]),
	[RequiresChemigation] [bit] NOT NULL,
	[RequiresWaterLevelInspection] [bit] NOT NULL,
	[WellDepth] [decimal](10, 4) NULL,
	[Clearinghouse] [varchar](100) NULL,
	[PageNumber] [int] NULL,
	[SiteName] [varchar](100) NULL,
	[SiteNumber] [varchar](100) NULL,
	[ScreenInterval] [varchar](100) NULL,
	[ScreenDepth] [decimal](10, 4) NULL,
	[OwnerName] [varchar](100) NULL,
	[OwnerAddress] [varchar](100) NULL,
	[OwnerCity] [varchar](100) NULL,
	[OwnerState] [varchar](20) NULL,
	[OwnerZipCode] [varchar](10) NULL,
	[AdditionalContactName] [varchar](100) NULL,
	[AdditionalContactAddress] [varchar](100) NULL,
	[AdditionalContactCity] [varchar](100) NULL,
	[AdditionalContactState] [varchar](20) NULL,
	[AdditionalContactZipCode] [varchar](10) NULL,
	[IsReplacement] [bit] NOT NULL,
	[Notes] [varchar](1000) NULL
)