CREATE TABLE [dbo].[AgHubIrrigationUnit](
	[AgHubIrrigationUnitID] [int] IDENTITY(1,1) NOT NULL,
	[WellTPID] [varchar](100) NOT NULL,
	[IrrigationUnitAreaInAcres] [float] NULL,
 CONSTRAINT [PK_AgHubIrrigationUnit_AgHubIrrigationUnitID] PRIMARY KEY CLUSTERED 
(
	[AgHubIrrigationUnitID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_AgHubIrrigationUnit_WellTPID] UNIQUE NONCLUSTERED 
(
	[WellTPID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
