CREATE TABLE [dbo].[OpenETSyncResultType](
	[OpenETSyncResultTypeID] [int] NOT NULL,
	[OpenETSyncResultTypeName] [varchar](100) NOT NULL,
	[OpenETSyncResultTypeDisplayName] [varchar](100) NOT NULL,
 CONSTRAINT [PK_OpenETSyncResultType_OpenETSyncResultTypeID] PRIMARY KEY CLUSTERED 
(
	[OpenETSyncResultTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_OpenETSyncResultType_AK_OpenETSyncResultTypeName] UNIQUE NONCLUSTERED 
(
	[OpenETSyncResultTypeName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_OpenETSyncResultType_OpenETSyncResultTypeDisplayName] UNIQUE NONCLUSTERED 
(
	[OpenETSyncResultTypeDisplayName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
