CREATE TABLE [dbo].[WellParticipation](
	[WellParticipationID] [int] NOT NULL,
	[WellParticipationName] [varchar](50) NOT NULL,
	[WellParticipationDisplayName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_WellParticipation_WellParticipationID] PRIMARY KEY CLUSTERED 
(
	[WellParticipationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_WellParticipation_WellParticipationDisplayName] UNIQUE NONCLUSTERED 
(
	[WellParticipationDisplayName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_WellParticipation_WellParticipationName] UNIQUE NONCLUSTERED 
(
	[WellParticipationName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
