CREATE TABLE [dbo].[FieldDefinitionType](
	[FieldDefinitionTypeID] [int] NOT NULL,
	[FieldDefinitionTypeName] [varchar](100) NOT NULL,
	[FieldDefinitionTypeDisplayName] [varchar](100) NOT NULL,
 CONSTRAINT [PK_FieldDefinitionType_FieldDefinitionTypeID] PRIMARY KEY CLUSTERED 
(
	[FieldDefinitionTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_FieldDefinitionType_FieldDefinitionTypeDisplayName] UNIQUE NONCLUSTERED 
(
	[FieldDefinitionTypeDisplayName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_FieldDefinitionType_FieldDefinitionTypeName] UNIQUE NONCLUSTERED 
(
	[FieldDefinitionTypeName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
