CREATE TABLE [dbo].[WellGroup](
	[WellGroupID] [int] IDENTITY(1,1) NOT NULL,
	[WellGroupName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_WellGroup_WellID] PRIMARY KEY CLUSTERED 
(
	[WellGroupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_WellGroup_WellGroupName] UNIQUE NONCLUSTERED 
(
	[WellGroupName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
