CREATE TABLE [dbo].[WaterLevelInspection](
	[WaterLevelInspectionID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_WaterLevelInspection_WaterLevelInspectionID] PRIMARY KEY,
	[WellID] [int] NOT NULL CONSTRAINT [FK_WaterLevelInspection_Well_WellID] FOREIGN KEY REFERENCES [dbo].[Well] ([WellID]),
	[InspectionDate] [datetime] NOT NULL,
	[InspectorUserID] [int] NOT NULL CONSTRAINT [FK_WaterLevelInspection_User_InspectorUserID_UserID] FOREIGN KEY REFERENCES [dbo].[User] ([UserID]),
	[WaterLevelInspectionStatus] [varchar](100) NULL,
	[MeasuringEquipment] [varchar](100) NULL,
	[Crop] [varchar](100) NULL,
	[HasOil] [bit] NOT NULL,
	[HasBrokenTape] [bit] NOT NULL,
	[Accuracy] [varchar](100) NULL,
	[Method] [varchar](100) NULL,
	[Party] [varchar](100) NULL,
	[SourceAgency] [varchar](100) NULL,
	[SourceCode] [varchar](100) NULL,
	[TimeDatumCode] [varchar](100) NULL,
	[TimeDatumReliability] [varchar](100) NULL,
	[LevelTypeCode] [varchar](100) NULL,
	[AgencyCode] [varchar](100) NULL,
	[Access] [varchar](100) NULL,
	[Hold] [decimal](12, 4) NULL,
	[Cut] [decimal](12, 4) NULL,
	[MP] [decimal](12, 4) NULL,
	[Measurement] [decimal](12, 4) NULL,
	[IsPrimary] [bit] NULL,
	[WaterLevel] [decimal](12, 2) NULL,
	[CropTypeID] [int] NULL CONSTRAINT [FK_WaterLevelInspection_CropType_CropTypeID] FOREIGN KEY REFERENCES [dbo].[CropType] ([CropTypeID]),
	[InspectionNotes] [varchar](500) NULL,
	[InspectionNickname] [varchar](100) NULL
)