CREATE TABLE [dbo].[CustomRichTextType](
	[CustomRichTextTypeID] [int] NOT NULL,
	[CustomRichTextTypeName] [varchar](100) NOT NULL,
	[CustomRichTextTypeDisplayName] [varchar](100) NOT NULL,
 CONSTRAINT [PK_CustomRichTextType_CustomRichTextTypeID] PRIMARY KEY CLUSTERED 
(
	[CustomRichTextTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_CustomRichTextType_CustomRichTextTypeDisplayName] UNIQUE NONCLUSTERED 
(
	[CustomRichTextTypeDisplayName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_CustomRichTextType_CustomRichTextTypeName] UNIQUE NONCLUSTERED 
(
	[CustomRichTextTypeName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
