CREATE TABLE [dbo].[WaterQualityInspection](
	[WaterQualityInspectionID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_WaterQualityInspection_WaterQualityInspectionID] PRIMARY KEY,
	[WellID] [int] NOT NULL CONSTRAINT [FK_WaterQualityInspection_Well_WellID] FOREIGN KEY REFERENCES [dbo].[Well] ([WellID]),
	[WaterQualityInspectionTypeID] [int] NOT NULL CONSTRAINT [FK_WaterQualityInspection_WaterQualityInspectionType_WaterQualityInspectionTypeID] FOREIGN KEY REFERENCES [dbo].[WaterQualityInspectionType] ([WaterQualityInspectionTypeID]),
	[InspectionDate] [datetime] NOT NULL,
	[InspectorUserID] [int] NOT NULL CONSTRAINT [FK_WaterQualityInspection_User_InspectorUserID_UserID] FOREIGN KEY REFERENCES [dbo].[User] ([UserID]),
	[Temperature] [decimal](12, 4) NULL,
	[PH] [decimal](12, 4) NULL,
	[Conductivity] [decimal](12, 4) NULL,
	[FieldAlkilinity] [decimal](12, 4) NULL,
	[FieldNitrates] [decimal](12, 4) NULL,
	[LabNitrates] [decimal](12, 4) NULL,
	[Salinity] [decimal](12, 4) NULL,
	[MV] [decimal](12, 4) NULL,
	[Sodium] [decimal](12, 4) NULL,
	[Calcium] [decimal](12, 4) NULL,
	[Magnesium] [decimal](12, 4) NULL,
	[Potassium] [decimal](12, 4) NULL,
	[HydrogenCarbonate] [decimal](12, 4) NULL,
	[CalciumCarbonate] [decimal](12, 4) NULL,
	[Sulfate] [decimal](12, 4) NULL,
	[Chloride] [decimal](12, 4) NULL,
	[SiliconDioxide] [decimal](12, 4) NULL,
	[CropTypeID] [int] NULL CONSTRAINT [FK_WaterQualityInspection_CropType_CropTypeID] FOREIGN KEY REFERENCES [dbo].[CropType] ([CropTypeID]),
	[PreWaterLevel] [decimal](12, 4) NULL,
	[PostWaterLevel] [decimal](12, 4) NULL,
	[InspectionNotes] [varchar](500) NULL,
	[InspectionNickname] [varchar](100) NULL
)