CREATE TABLE [dbo].[ChemicalUnit](
	[ChemicalUnitID] [int] NOT NULL,
	[ChemicalUnitName] [varchar](100) NULL,
	[ChemicalUnitPluralName] [varchar](100) NULL,
	[ChemicalUnitLowercaseShortName] [varchar](100) NULL,
 CONSTRAINT [PK_ChemicalUnit_ChemicalUnitID] PRIMARY KEY CLUSTERED 
(
	[ChemicalUnitID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_ChemicalUnit_ChemicalUnitLowercaseShortName] UNIQUE NONCLUSTERED 
(
	[ChemicalUnitLowercaseShortName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_ChemicalUnit_ChemicalUnitName] UNIQUE NONCLUSTERED 
(
	[ChemicalUnitName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_ChemicalUnit_ChemicalUnitPluralName] UNIQUE NONCLUSTERED 
(
	[ChemicalUnitPluralName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
